# Colorized Output Setup
if(NOT WIN32)
  string(ASCII 27 Esc)
  set(reset 		"${Esc}[m")
  set(bold  		"${Esc}[1m")
  set(red         	"${Esc}[31m")
  set(green       	"${Esc}[32m")
  set(blue        	"${Esc}[34m")
  set(cyan        	"${Esc}[36m")
  set(magenta     	"${Esc}[35m")
  set(yellow      	"${Esc}[33m")
  set(white       	"${Esc}[37m")
  set(bold_red     	"${Esc}[1;31m")
  set(bold_green   	"${Esc}[1;32m")
  set(bold_blue    	"${Esc}[1;34m")
  set(bold_cyan    	"${Esc}[1;36m")
  set(bold_magenta 	"${Esc}[1;35m")
  set(bold_yellow  	"${Esc}[1;33m")
  set(bold_white   	"${Esc}[1;37m")
endif()
